book/urls.py
from django.urls import path
from .views import HomeListView, BookDetailView, BorrowBtn, ReturnBtn, Search, BookListView
app_name = 'book'
urlpatterns = [
    path('', HomeListView.as_view(), name='book'),
    path('books/', BookListView.as_view(), name='list_book'),
    path('book/<int:pk>/', BookDetailView.as_view(), name='book_detail'),
    path('borrow/<int:pk>', BorrowBtn.as_view(), name='book_borrow'),
    path('return/<int:pk>', ReturnBtn.as_view(), name='book_return'),
    path('search/', Search.as_view(), name='search'),



]

category/urls.py
from django.urls import path
from .views import CategoryListView, CategoryDetailView
app_name = 'category'
urlpatterns = [
    path('', CategoryListView.as_view(), name='category'),
    path('category/<int:pk>', CategoryDetailView.as_view(), name='detail'),


]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('student.urls')),  # new
    path('accounts/', include('django.contrib.auth.urls')),  # new

    path('', include('book.urls', namespace='book')),
    path('categories/', include('category.urls', namespace='category')),
    path('myadmin/', include('myadmin.urls', namespace='myadmin')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myadmin/urls.py
from django.urls import path
from .views import BookCreateView, BookUpdateView, BookDeleteView, CategoryDeleteView, CategoryUpdateView, CategoryCreateView

app_name = 'myadmin'
urlpatterns = [
    path('add_book/', BookCreateView.as_view(), name="add_book"),
    path('edit_book/<int:pk>/', BookUpdateView.as_view(), name="edit_book"),
    path('delete_book/<int:pk>/', BookDeleteView.as_view(), name="delete_book"),
    path('add_category/', CategoryCreateView.as_view(), name="add_category"),
    path('edit_category/<int:pk>/',
         CategoryUpdateView.as_view(), name="edit_category"),
    path('delete_category/<int:pk>/',
         CategoryDeleteView.as_view(), name="delete_category"),


]

category/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Category(models.Model):
    title = models.CharField(max_length=200)
    # student = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    img = models.ImageField(upload_to='category/images/')

    def __str__(self):
        return self.title

    def get_absolute_url(self):  # new
        return reverse('category:detail', args=[str(self.id)])

category/views.py
from django.shortcuts import render
# , CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
#from .models import Book
from category.models import Category
# Create your views here.


class CategoryListView(ListView):

    model = Category
    template_name = "category/home.html"
    context_object_name = 'categories'


class CategoryDetailView(DetailView):
    model = Category
    template_name = "category/category_detail.html"

templates/category/category_detail.html
{% extends "layout/base.html" %}
{% load static %}
{% block library %}
<link rel="stylesheet" href="{% static "book/css/home.css" %}">
<link rel="stylesheet" href="{% static "myadmin/css/delete_edit.css" %}">

<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
    integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
{% if user.is_staff %}


<a class='delete_btn' href=" {% url 'myadmin:delete_category' category.pk %}"><i class="fas fa-trash"></i></a>
<a class='edit_btn' href="{% url 'myadmin:edit_category' category.pk %}"><i class="fas fa-edit"></i></a>

{%endif%}
<h3>{{category.title}} Books</h3>
<div class="cards__container">


    {% for book in category.books.all %}
    <div class="card">
        <img class="book_img" src="{{book.img.url}}" alt="" />
        <p class="name">{{book.title}}</p>
        <p class=" author">{{book.author}}</p>
        <p class="status">{{book.status}}</p>
        <a href="{%url 'book:book_detail' book.pk %}"><button class="book_btn">view details</button></a>
    </div>
    {% endfor %}
</div>
<script src="{% static "book/js/book_status.js" %}"></script>

{% endblock library %}

templates/category/home.html
{% extends "layout/base.html" %}
{% load static %}
{% block library %}

<link rel="stylesheet" href="{% static "book/css/home.css" %}">
<link rel="stylesheet" href="{% static "myadmin/css/delete_edit.css" %}">
{% if user.is_staff %}
<a class='edit_btn' href=" {% url 'myadmin:add_category' %}">Add Category</a>

{% endif %}

<h3>All Categories</h3>
<div class="cards__container">
    {% for category in categories %}
    <div class="cat_card">
        <img class="cat_img" src="{{category.img.url}}" alt="" />
        <p class="cat_name">{{category.title}}</p>
        <p class="author">{{category.books.count}}</p>
        <a href="{% url 'category:detail' category.pk %}"><button class="cat_book_btn">view all</button></a>
    </div>
    {% endfor %}
</div>
{% endblock library %}