book/urls.py
from django.urls import path
from .views import HomeListView, BookDetailView, BorrowBtn, ReturnBtn, Search, BookListView
app_name = 'book'
urlpatterns = [
    path('', HomeListView.as_view(), name='book'),
    path('books/', BookListView.as_view(), name='list_book'),
    path('book/<int:pk>/', BookDetailView.as_view(), name='book_detail'),
    path('borrow/<int:pk>', BorrowBtn.as_view(), name='book_borrow'),
    path('return/<int:pk>', ReturnBtn.as_view(), name='book_return'),
    path('search/', Search.as_view(), name='search'),



]

category/urls.py
from django.urls import path
from .views import CategoryListView, CategoryDetailView
app_name = 'category'
urlpatterns = [
    path('', CategoryListView.as_view(), name='category'),
    path('category/<int:pk>', CategoryDetailView.as_view(), name='detail'),


]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('student.urls')),  # new
    path('accounts/', include('django.contrib.auth.urls')),  # new

    path('', include('book.urls', namespace='book')),
    path('categories/', include('category.urls', namespace='category')),
    path('myadmin/', include('myadmin.urls', namespace='myadmin')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myadmin/urls.py
from django.urls import path
from .views import BookCreateView, BookUpdateView, BookDeleteView, CategoryDeleteView, CategoryUpdateView, CategoryCreateView

app_name = 'myadmin'
urlpatterns = [
    path('add_book/', BookCreateView.as_view(), name="add_book"),
    path('edit_book/<int:pk>/', BookUpdateView.as_view(), name="edit_book"),
    path('delete_book/<int:pk>/', BookDeleteView.as_view(), name="delete_book"),
    path('add_category/', CategoryCreateView.as_view(), name="add_category"),
    path('edit_category/<int:pk>/',
         CategoryUpdateView.as_view(), name="edit_category"),
    path('delete_category/<int:pk>/',
         CategoryDeleteView.as_view(), name="delete_category"),


]

book/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
from category.models import Category
from config import settings
# Create your models here.


class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=200)
    # student = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name="books", null=True)
    student = models.ForeignKey(
        get_user_model(), on_delete=models.SET_NULL, related_name="books", null=True, blank=True)
    description = models.TextField()
    img = models.ImageField(upload_to='book/images/', )
    status = models.CharField(
        max_length=10,
        choices=[
            ("Available", "a"),
            ("Borrowed", "b")
        ], default="Available"
    )
    return_date = models.DateField(
        auto_now=False, auto_now_add=False, null=True, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):  # new
        return reverse('book:book_detail', args=[str(self.pk)])

book/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, DetailView
from django.views import View
from .models import Book
from category.models import Category
from student.models import CustomUser

# Create your views here.


class BookListView(ListView):
    model = Book
    template_name = "book/book_list.html"
    context_object_name = 'books'


class HomeListView(ListView):

    model = Book
    template_name = "book/home.html"
    context_object_name = 'books'

    def get_context_data(self,  **kwargs):
        # student = self.request.user
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()[
            :5]
        context['students'] = CustomUser.objects.all()[:5]
        # context['student1'] = student
        # print(student.books)
        return context


class BookDetailView(DetailView):
    model = Book
    template_name = "book/book_detail.html"


class BorrowBtn(LoginRequiredMixin, View):
    template_name = 'book/home.html'

    def post(self, request,  * args, **kwargs):

        book = get_object_or_404(Book, pk=kwargs['pk'])
        book.return_date = request.POST["return_date"]
        book.status = 'Borrowed'
        # std_pk = int(request.user.id)get_object_or_404(CustomUser, pk=std_pk)
        custom_user = request.user
        book.student = custom_user
        book.save()
        return redirect('book:book_detail', kwargs['pk'])

    def get(self, request, *args, **kwargs):

        return redirect('book:book')


class ReturnBtn(LoginRequiredMixin, View):

    def post(self, request,  * args, **kwargs):

        book = get_object_or_404(Book, pk=kwargs['pk'])
        book.return_date = None
        book.status = 'Available'
        book.student = None
        book.save()
        return redirect('book:book_detail', kwargs['pk'])

    def get(self, request, *args, **kwargs):

        return redirect('book:book')


class Search(View):

    def post(self, request,  * args, **kwargs):
        searchname = request.POST["search"]
        if searchname == '':
            return redirect('book:book')
        books = Book.objects.filter(title__startswith=searchname)
        books = books | Book.objects.filter(author__startswith=searchname)
        students = []
        if request.user.is_staff:
            students = CustomUser.objects.filter(
                first_name__startswith=searchname)
        return render(request, 'book/search.html', {'students': students, 'books': books})

    def get(self, request, *args, **kwargs):

        return redirect('book:book')

templates/book/book_detail.html
{% extends "layout/base.html" %}
{% load static %}
{% block library %}
<link rel="stylesheet" href="{% static "book/css/book_detail.css" %}">
<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
    integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />


<h3>Book details</h3>
<div class="container">
    <img src="{{object.img.url}} " alt="" class="book_img">
    <p class="name">{{object.title}}</p>
    <p class="author">{{object.author}} </p>
    <p class="cat">{{object.category}} </p>
    <p class="desc">{{object.description}} </p>
    <p class="status">{{book.status}}</p>

    {% if book.student and user.is_staff%}
    <p class="id">Student: <a id='std_name' href="{{book.student.get_absolute_url}}">{{book.student.first_name}}
            {{book.student.last_name}} </a></p>

    {% endif %}
    {% if book.status == 'Borrowed' %}

    <p class=" availability"> will be available at: {{object.return_date}} </p>
    {% endif %}


    {% if user.is_staff %}


    <a class='delete_btn' href=" {% url 'myadmin:delete_book' book.pk %}"><i class="fas fa-trash"></i></a>
    <a class='edit_btn' href="{% url 'myadmin:edit_book' book.pk %}"><i class="fas fa-edit"></i></a>

    {%else%}

    <form class="borrow_form" id="borrow_form" action="{% url 'book:book_borrow' book.pk %}" method="POST">
        {% csrf_token %}
        <input type="date" onchange="myfun()" class="return_date text_box" id="return_date" title="set return date"
            name="return_date" autocomplete="off" required />

        <button type='submit' class="borrow_btn" id="borrow_btn">Set return date</button>
    </form>
    <!-- <a href="{% url 'book:book_return'  book.pk %}">back to shelf</a> -->
    {% if book.student == user %}


    <form class="form" id="return_form" action="{% url 'book:book_return' book.pk %}" method="POST">
        {% csrf_token %}


        <button class="return_btn" id="return_btn">return</button>
    </form>
    {%else%}
    <form class="form" id="return_form" action="{% url 'book:book' %}" method="get">
        {% csrf_token %}


        <button class="return_btn" id="return_btn">back to shelf</button>
    </form>
    {% endif %}
    {% endif %}


</div>
<h3>Related Books</h3>
<div class="cards__container">
    {% for book in book.category.books.all|slice:'4' %}

    <div class="card">
        <img class="book_img2" src="{{book.img.url}}" alt="" />
        <p class="name2">{{book.title}}</p>
        <p class=" author2">{{book.author}}</p>
        <p class="status2">{{book.status}}</p>

        <a href="{%url 'book:book_detail' book.pk %}"><button class="book_btn">view details</button></a>
    </div>
    {% endfor %}
</div>
<script src="{% static "book/js/book_details.js" %}"></script>


{% endblock library %}

templates/book/book_list.html
{% extends "layout/base.html" %}


{% load static %}

{% block library %}

<link rel="stylesheet" href="{% static "book/css/home.css" %}">
<h3>All Books</h3>

<div class="cards__container">
    {% for book in books  %}


    <div class="card">
        <img class="book_img" src="{{book.img.url}}" alt="" />
        <p class="name">{{book.title}}</p>
        <p class=" author">{{book.author}}</p>
        <p class="status">{{book.status}}</p>
        <a href="{%url 'book:book_detail' book.pk %}"><button class="book_btn">view details</button></a>
    </div>
    {% endfor %}


</div>
<script src="{% static "book/js/book_status.js" %}"></script>

{% endblock library%}

templates/book/home.html
{% extends "layout/base.html" %}


{% load static %}

{% block library %}

<link rel="stylesheet" href="{% static "book/css/home.css" %}">


{% if user.is_staff %}
<h3>Students</h3>
<div class="cards__container">

    {% for student in students %}
    <div class="std_card card">
        <img class="std_img" src="{{student.img.url}}" alt="" />
        <p class="name">{{student.first_name}}{{student.last_name}}</p>
        <p class="author">ID {{student.id}}</p>
        <p class="status">borrow {{student.books.all.count}} books</p>


        <a href="{% url "std_profile" student.pk%}" class="book_btn">view more info</a>
    </div>
    {%endfor%}
    <a class='category book_btn' href="{% url 'student_list' %}" title="log out">All Students</a>

</div>

{% endif %}
{% if user.is_authenticated and not user.is_staff %}
<h3>My Books</h3>
<div class="cards__container">
    {% if user.books.all.count < 1 %}


    <h2 id="no_books">you don't borrowed any books</h2>

    {%else%}
    {% for book in user.books.all  %}
    <div class="card">
        <img class="book_img" src="{{book.img.url}}" alt="" />
        <p class="name">{{book.title}}</p>
        <p class=" author">{{book.author}}</p>
        <p class="status">{{book.status}}</p>
        <a href="{%url 'book:book_detail' book.pk %}"><button class="book_btn">view details</button></a>
    </div>


    {% endfor %}
    {% endif %}

</div>

{% endif %}
<h3>Books</h3>

<div class="cards__container">
    {% for book in books|slice:"0:5"  %}


    <div class="card">
        <img class="book_img" src="{{book.img.url}}" alt="" />
        <p class="name">{{book.title}}</p>
        <p class=" author">{{book.author}}</p>
        <p class="status">{{book.status}}</p>
        <a href="{%url 'book:book_detail' book.pk %}"><button class="book_btn">view details</button></a>
    </div>
    {% endfor %}
    <a class='category book_btn' href="{% url 'book:list_book' %}" title="log out">All Books</a>

</div>
<h3>Categories</h3>
<div class="cards__container">
    {% for category in categories  %}


    <div class="cat_card">
        <img class="cat_img" src="{{category.img.url}}" alt="" />
        <p class="cat_name">{{category.title}}</p>
        <p class="author">{{category.books.count}}</p>
        <a href="{% url 'category:detail' category.pk %}"><button class="cat_book_btn">view all</button></a>
    </div>
    {% endfor %}
    <a class='category book_btn' href="{% url 'category:category' %}" title="log out">All Categories</a>

</div>

<script src="{% static "book/js/book_status.js" %}"></script>


{% endblock library %}

templates/book/search.html
{% extends "layout/base.html" %}
{% load static %}
{% block library %}
<link rel="stylesheet" href="{% static "book/css/home.css" %}">

<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
    integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />

<h3>search results</h3>
<hr>
{% if user.is_staff %}
<h3>Students</h3>

<div class="cards__container">
    {% for student in students %}
    <div class="card">
        <img class="book_img" src="{{student.img.url}}" alt="" />
        <p class="name">{{student.first_name}}{{student.last_name}}</p>
        <p class="author">ID {{student.id}}</p>
        <a href="{% url "std_profile" student.pk%}" class="book_btn">view more info</a>
    </div>
    {% endfor %}

    {% endif %}
</div>
<h3>Book</h3>

<div class="cards__container">

    {% for book in books %}


    <div class="card">
        <img class="book_img" src="{{book.img.url}}" alt="" />
        <p class="name">{{book.title}}</p>
        <p class=" author">{{book.author}}</p>
        <p class="status">{{book.status}}</p>
        <a href="{%url 'book:book_detail' book.pk %}"><button class="book_btn">view details</button></a>
    </div>
    {% endfor %}
</div>
<script src="{% static "book/js/book_status.js" %}"></script>

{% endblock library %}