book/urls.py
from django.urls import path
from .views import HomeListView, BookDetailView, BorrowBtn, ReturnBtn, Search, BookListView
app_name = 'book'
urlpatterns = [
    path('', HomeListView.as_view(), name='book'),
    path('books/', BookListView.as_view(), name='list_book'),
    path('book/<int:pk>/', BookDetailView.as_view(), name='book_detail'),
    path('borrow/<int:pk>', BorrowBtn.as_view(), name='book_borrow'),
    path('return/<int:pk>', ReturnBtn.as_view(), name='book_return'),
    path('search/', Search.as_view(), name='search'),



]

category/urls.py
from django.urls import path
from .views import CategoryListView, CategoryDetailView
app_name = 'category'
urlpatterns = [
    path('', CategoryListView.as_view(), name='category'),
    path('category/<int:pk>', CategoryDetailView.as_view(), name='detail'),


]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('student.urls')),  # new
    path('accounts/', include('django.contrib.auth.urls')),  # new

    path('', include('book.urls', namespace='book')),
    path('categories/', include('category.urls', namespace='category')),
    path('myadmin/', include('myadmin.urls', namespace='myadmin')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myadmin/urls.py
from django.urls import path
from .views import BookCreateView, BookUpdateView, BookDeleteView, CategoryDeleteView, CategoryUpdateView, CategoryCreateView

app_name = 'myadmin'
urlpatterns = [
    path('add_book/', BookCreateView.as_view(), name="add_book"),
    path('edit_book/<int:pk>/', BookUpdateView.as_view(), name="edit_book"),
    path('delete_book/<int:pk>/', BookDeleteView.as_view(), name="delete_book"),
    path('add_category/', CategoryCreateView.as_view(), name="add_category"),
    path('edit_category/<int:pk>/',
         CategoryUpdateView.as_view(), name="edit_category"),
    path('delete_category/<int:pk>/',
         CategoryDeleteView.as_view(), name="delete_category"),


]

templates/layout/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
        integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />

    <link rel="stylesheet" href=" {% static "book/css/base.css" %}">
    <title>Document</title>
</head>

<body>


    <header>
        <span class="logo">
            <a href="{% url 'book:book' %}"><i class="fas fa-book-open logoo"></i></a>
        </span>
        <form action="{% url 'book:search' %}" method="post">
            {% csrf_token %}
            <div class="search_container">
                <input type="text" class="search" id="search_id" placeholder="Discover new books" name="search"
                    autocomplete="off" />
                <button type="submit" class="search_btn">
                    <i class="fas fa-search"></i>
                </button>
            </div>
        </form>

        {% if user.is_authenticated%}
        {% if user.is_staff %}


        <a class='category' href="{% url 'myadmin:add_book' %}" title="log out">Add Book</a>
        {%else%}
        <a class='category' href="{% url 'category:category' %}" title="log out"></a>

        {% endif %}
        <a class="profile_btn" href="{% url 'std_profile' user.pk %}" title="go to profile"><i
                class="fas fa-user"></i></a>

        <a class="logout_btn" href="{% url 'logout' %}" title="log out"><i class="fas fa-sign-out-alt"></i></a>
        {% else %}
        <a class='category' href="{% url 'category:category' %}" title="log out"></a>

        <a class='login' href="{% url 'login' %}" title="log out">Log In</a>
        <a class='login' href="{% url 'signup' %}" title="log out">Sign Up</a>
        {% endif %}
    </header>

    {% block library %}

    {% endblock library %}

</body>

</html>